### PR TITLE
Minimized open layers with the new di.cfg

### PR DESCRIPTION
**Pull request by ziroby**
Minimized open layers with the new di.cfg

### CODE REVIEW

**Comment by gregsymons** [comment]
LGTM, but can you rebase, rebuild, and squash so we can get @nbalaatdrillinginfo's change to fix multiple text nodes in WFS?

**Comment by ziroby** [comment]
Done.  Please re-review.

**Comment by ziroby** [comment]
Really done.  Please re-review.

**Comment by gregsymons** [comment]
:shipit:

**Pull request merged**
